### ISSUE TITLE
Possibility to add Year Metadata

### ISSUE THREAD

**Issue by arnaudgst** [vladkorotnev/traktor-obs-relay#5]
Hello, 

First of all, Thank You :)

>> Is it possible to add the "Year" Metadata to list of the available Vars ?

Regards,

Arno

**Comment by vladkorotnev** [comment]
Similarly, it's not exposed via the API sadly so it'll have to be implemented on that project side first https://github.com/ErikMinekus/traktor-api-client/blob/main/D2/Api/ApiDeck.qml#L73

**Comment by vladkorotnev** [comment]
Close for the time being as requiring implementation on the other side of things first
